```{r}
print("Vectors")

#Vector and vector operations basics
```

```{r}
#Creating vectors

createvector1 <- c("ahri", "anivia", "azir", "bard")
print(createvector1)

createvector2 <- assign("botlane",c("xayah", "rakan", "caitlyn"))
print(createvector2)
names(createvector2) #NULL

#Colon assigns consecutive numbers
createvector3 <- 1:10
print(createvector3)

#Assigns an arithmetic progression
#seq(lower limit, upper limit, increment)
createvector4 <- seq(1,5,1.5)
print(createvector4)

#Replicate elements
#rep(start:end, times)
createvector5 <- rep(2:5,times=3)
print(createvector5)

#Get is input
createvector6 <- scan()
```
```{r}
attributeVector <- c("riven", "ahri", "xayah", "rakan", "warwick", 2, 5)

print(length(attributeVector))
#If mixed type, implicit conversion occurs
print(typeof(attributeVector))
print(is.vector(attributeVector))

nameVector <- c("top", "mid", "bot", "supp", "jngl", "num1", "num2")
names(attributeVector) <- nameVector
print(names(attributeVector))
print(attributeVector)

attributeVector2 <- c("top"="quinn")
print(names(attributeVector2))

```

```{r}
sortvector1 <- c("darius", "jayce", "ahri", "quinn", "pyke", "graves")
print(sort(sortvector1))
#Better use numbers lol. Should return the position when sorted
print(order(sortvector1))

#Index starts from 1
print(sortvector1[1])
#To pick using name a["name"]
print(sortvector1[2:5])

#Except 2nd element
print(sortvector1[-2])
#2nd and 4th element
print(sortvector1[c(2,4)])
#Omits 4th and 5th
print(sortvector1[-(4:5)])

```
```{r}
sortVector2 <- c(1,4,3,2,5,7,6,8,1)
print(order(sortVector2))

#All 1s
print(sortVector2[sortVector2 == 1])

#Elements greater than 4
print(sortVector2[sortVector2 > 4])

#Returns if elements are there in list
print(sortVector2[sortVector2 %in% c(3,7,5)])

#Sorting
print(sort(sortVector2,decreasing = TRUE))

#Maximum element
print(max(sortVector2))

#Name and position of greatest element
print(which.max(sortVector2))

rank(sortVector2)

```
```{r}
#Shorter vector is repeated to length of longer vector
vector1 <- c(1,1)
vector2 <- c(2,2,2,2)

print(vector1 + vector2)
print(vector2 - vector1)
print(vector1 * vector2)
print(vector1 == vector2)

```

